# 5-3. 패키지

## 패키지란 무엇인가?
패키지는 도트(.)를 사용하여 파이썬 모듈을 계층적으로 관리할 수 있게 해준다. 예를 들어 모듈 이름이 A.B인 경우에 A는 패키지 이름이 되고, B는 A패키지의 B모듈이 된다.  
  
즉 패키지는 모듈을 여러개 모아놓은 것이라고 할 수 있다.
> 파이썬에서 모듈은 하나의 .py 파일이다.
  
파이썬 패키지는 디렉터리와 파이썬 모듈로 이루어지며 구조는 다음과 같다.
  
*가상의 game패키지 예*
```
game/
    __init__.py
    sound/
        __init__.py
        echo.py
        wav.py
    graphic/
        __init__.py
        screen.py
        render.py
    play/
        __init__.py
        run.py
        test.py
```
game, sound, graphic, play는 디렉터리이며, 확장자가 .py인 파일은 파이썬 모듈이다.   
game 디렉터리가 이 패키지의 루트 디렉터리이고 sound, graphic, play는 서브 디렉터리이다.  
  
간단한 파이썬 프로그램이 아니라면 이렇게 패키지 구조로 파이썬 프로그램을 만드는 것이 공동 작업이나 유지 보수 등 여러 면에서 유리하다. 또한 패키지 구조로 모듈을 만들면 다른 모듈과 이름이 겹쳐도 더 안전하게 사용할 수 있다.

## 패키지 만들기
**패키지 기본 구성 요소 준비하기**
  
1. `C:/doit` 디렉터리 밑에 game 및 기타 서브 디렉터리를 생성하고 .py 파일들을 다음과 같이 만들어 보자
```
C:/doit/game/__init__.py
C:/doit/game/sound/__init__.py
C:/doit/game/sound/echo.py
C:/doit/game/graphic/__init__.py
C:/doit/game/graphic/render.py
```
  
2. 각 디렉터리에 `__init__.py` 파일을 만들어 놓기만 하고 내용은 일단 비워 둔다.
  
3. echo.py 파일은 다음과 같이 만든다.
``` python
# echo.py
def echo_test():
    print("echo")
```
  
4. render.py 파일은 다음과 같이 만든다.
``` python
# render.py
def render_test():
    print("render")
```

## 패키지 안의 함수 실행하기

패키지를 사용해 echo.py 파일의 echo_test 함수를 실행해 보자. 패키지 안의 함수를 실행하는 방법은 3가지가 있다.
  
1. echo 모듈(echo.py 파일)을 import하여 실행 
``` python
>>> import game.sound.echo
>>> game.sound.echo.echo_test()
echo
```

2. echo 모듈이 있는 디렉터리까지를 from ... import하여 실행
``` python
>>> from game.sound import echo
>>> echo.echo_test()
echo
```

3. echo 모듈의 echo_test 함수를 직접 import하여 실행
``` python
>>> from game.sound.echo import echo_test
>>> echo_test()
echo
```
  
하지만 다음과 같이 echo_test 함수를 사용하는 것은 불가능하다.
  
> ※ 다음 예제는 반드시 파이썬 인터프리터를 종료하고 다시 실행해야 한다.
  
```python
>>> import game
>>> game.sound.echo.echo_test()
```
import game을 수행하면 game 디렉터리의 `__init__.py`에 정의한 것만 참조할 수 있다.
  
```python
>>> import game.sound.echo.echo_test
```
도트 연산자(.)를 사용해서 import a.b.c 처럼 import할 때 가장 마지막 항목 c는 반드시 모듈 또는 패키지여야만 한다.

## `__init__.py`의 용도

이 파일은 해당 디렉터리가 패키지의 일부임을 알려주는 역할을 한다.  
패키지에 포함된 디렉터리(game, sound, graphic 등)에 `__init__.py` 파일이 없다면 패키지로 인식되지 않는다.
  
> ※ python3.3 버전부터는 `__init__.py` 파일이 없어도 패키지로 인식한다. 하지만 하위 버전 호환을 위해 `__init__.py` 파일을 생성하는 것이 안전한 방법이다.  

* `__all__` 변수의 설정

```python
>>> from game.sound import *
>>> echo.echo_test()
Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
NameError: name 'echo' is not defined
```
game.sound 패키지에서 모든 것(`*`)을 import하였으므로 echo 모듈을 사용할 수 있어야 할 것 같은데 echo라는 이름이 정의되지 않았다는 NameError가 발생한다.
  
이렇게 특정 디렉터리의 모듈을 `*`를 사용하여 import할 때에는 다음과 같이 해당 디렉터리의 `__init__.py` 파일에 `__all__` 변수를 설정하고 import할 수 있는 모듈을 정의해 주어야 한다.

```
# C:/doit/game/sound/__init__.py
__all__ = ['echo']
```

여기서 `__all__`이 의미하는 것은 sound 디렉터리에서 * 기호를 사용하여 import할 경우 이곳에 정의된 `echo` 모듈만 import된다는 의미이다.
  
> ※ from game.sound.echo import * 는 `__all__`과 상관없이 무조건 import된다.  
> from a.b.c import * 에서 from의 마지막 항목인 c가 모듈인 경우!
  
위와 같이 `__init__.py` 파일을 변경한 후 위 예제를 수행하면 원하던 결과가 출력되는 것을 확인할 수 있다.
``` python
>>> from game.sound import *
>>> echo.echo_test()
echo
```

## relative 패키지

graphic 디렉터리의 render.py모듈이 sound 디렉터리의 echo.py 모듈을 사용하고 싶다면 다음과 같이 render.py 를 수정해야한다.
``` python
# render.py
from game.sound.echo import echo_test #추가
def render_test():
    print("render")
    echo_test() #추가
```
`from game.sound.echo import echo_test` 문장을 추가해 `echo_test` 함수를 사용할 수 있도록 수정했다.
  
``` python
>>> from game.graphic.render import render_test
>>> render_test()
render
echo
```
이 후 다음과 같이 실행하면 이상없이 잘 수행되는 것을 확인할 수 있다.
  
    
위 예제처럼 전체 경로를 사용하여 import할 수도 있지만 다음과 같이 relative하게 import하는 것도 가능하다.
```python
# render.py
from ..sound.echo import echo_test

def render_test():
    print("render")
    echo_test() 
```
`from game.sound.echo import echo_test`가 `from ..sound.echo import echo_test`로 변경되었다.  
여기에서 `..`은 render.py 파일의 부모 디렉터리를 의미한다. 따라서 render.py 파일의 부모 디렉터리는 game이므로 위와 같은 import가 가능한 것이다.

> ※ render.py 파일의 현재 디렉터리는 graphic이고 부모 디렉터리는 game이다.

relative한 접근자에는 다음과 같은 것이 있다.

`..` – 부모 디렉터리  
`.` – 현재 디렉터리

---

# 5-4. 예외 처리
파이썬에서 오류가 발생하면 프로그램이 중단된다.  
발생하는 오류를 무시하고 싶을 때 try, except를 사용해서 예외적으로 오류를 처리할 수 있게 해준다.

## 오류는 어떤 때 발생하는가?
실제 프로그램에서 자주 발생하는 오류를 중심으로 살펴보자.
  
먼저, 디렉터리 안에 없는 파일을 열려고 시도했을 때 발생하는 오류이다.  
없는 파일을 열려고 시도하면 FileNotFoundError 오류가 발생한다.
``` python
>>> f = open("나없는파일", 'r')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '나없는파일'
```

0으로 다른 숫자를 나누는 경우를 생각해 보자.  
4를 0으로 나누려니까 ZeroDivisionError 오류가 발생한다.
``` python
>>> 4 / 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
```

마지막으로, 빈번하게 나타나는 오류를 살펴보자.
```python
>>> a = [1,2,3]
>>> a[4]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
```
a는 리스트 [1, 2, 3]인데 a[4]는 a 리스트에서 얻을 수 없는 값이기 때문에 IndexError 오류가 발생한다.   
파이썬은 이런 오류가 발생하면 프로그램을 중단하고 오류 메시지를 보여 준다.

## 오류 예외 처리 기법

### try, except문
```
try:
    ...
except [발생 오류[as 오류 메시지 변수]]:
    ...
```
try 블록 수행 중 오류가 발생하면 except 블록이 수행된다. 하지만 try 블록에서 오류가 발생하지 않는다면 except 블록은 수행되지 않는다.  
except 구문에서 [ ] 기호를 사용하는데, 이 기호는 괄호 안의 내용을 생략할 수 있다는 관례 표기법이다. 즉 except 구문은 다음 3가지 방법으로 사용할 수 있다.

1. try, except만 쓰는 방법  
이 경우는 오류 종류에 상관없이 오류가 발생하면 except 블록을 수행한다.
```
try:
    ...
except:
    ...
```

2. 발생 오류만 포함한 except문  
이 경우는 오류가 발생했을 때 except문에 미리 정해 놓은 오류 이름과 일치할 때만 except 블록을 수행한다는 뜻이다.
```
try:
    ...
except 발생 오류:
    ...
```

3. 발생 오류와 오류 메시지 변수까지 포함한 except문  
이 경우는 오류 메시지의 내용까지 알고 싶을 때 사용하는 방법이다.
```
try:
    ...
except 발생 오류 as 오류 메시지 변수:
    ...
```
예를 들어보면 다음과 같다.
```python
>>> try:
>>>    4 / 0
>>> except ZeroDivisionError as e:
>>>    print(e)
division by zero
```
위처럼 4를 0으로 나누려고 하면 ZeroDivisionError가 발생하여 except 블록이 실행되고 변수 e에 담기는 오류 메시지를 다음과 같이 출력한다.

### try .. finally  
try문에는 finally절을 사용할 수 있다. finally절은 try문 수행 도중 예외 발생 여부에 상관없이 항상 수행된다.  
보통 finally절은 사용한 리소스를 close해야 할 때에 많이 사용한다.  
  
예를 들으면 다음과 같다.
```
f = open('foo.txt', 'w')
try:
    # 무언가를 수행한다.
finally:
    f.close()
```
foo.txt 파일을 쓰기 모드로 연 후에 try문을 수행한 후 예외 발생 여부와 상관없이 finally절에서 f.close()로 열린 파일을 닫을 수 있다.

### 여러 개의 오류 처리하기
try 문 안에서 여러 개의 오류를 처리하기 위해 다음 구문을 사용한다.
```
try:
    ...
except 발생 오류1:
   ... 
except 발생 오류2:
   ...
```

예를 들어보면 다음과 같다.
```python
>>> try:
>>>     a = [1,2]
>>>     print(a[3])
>>>     4/0
>>> except ZeroDivisionError:
>>>     print("0으로 나눌 수 없습니다.")
>>> except IndexError:
>>>     print("인덱싱 할 수 없습니다.") 
인덱싱 할 수 없습니다.
```
a[3]는 IndexError를 발생시키므로 "인덱싱할 수 없습니다."라는 문자열이 출력된다.  
인덱싱 오류가 먼저 발생했으므로 4/0으로 발생되는 ZeroDivisionError 오류는 발생하지 않는다.  
  
다음과 같이 오류 메시지를 직접 가져올 수도 있다.  
``` python
>>> try:
>>>     a = [1,2]
>>>     print(a[3])
>>>     4/0
>>> except ZeroDivisionError as e:
>>>     print(e)
>>> except IndexError as e:
>>>     print(e)
list index out of range
```

또한 다음과 같이 `ZerroDivisionError`와 `IndexError`를 함께 처리할 수도 있다.
```python
>>> try:
>>>     a = [1,2]
>>>     print(a[3])
>>>     4/0
>>> except (ZeroDivisionError, IndexError) as e:
>>>     print(e)
list index out of range
```
2개 이상의 오류를 동일하게 처리하기 위해서는 위와 같이 괄호를 사용하여 함께 묶어 처리하면 된다.

> **try문에 else절 사용하기**
> try문에는 else절을 사용할 수 있다.
> ```
> try:
>     ...
> except [발생 오류[as 오류 메시지 변수]]:
>     ...
> else:  # 오류가 없을 경우에만 수행된다.
>     ...
> ```
> try문 수행중 오류가 발생하면 except절이 수행되고 오류가 없으면 else절이 수행된다.   
> 예를 들어보자.
> ```python
> try:
>     age=int(input('나이를 입력하세요: '))
> except:
>     print('입력이 정확하지 않습니다.')
> else:
>     if age <= 18:
>         print('미성년자는 출입금지입니다.')
>     else:
>         print('환영합니다.')
> ```
>  만약 '나이를 입력하세요:' 라는 질문에 숫자가 아닌 다른 값을 입력하면 오류가 발생하여 '입력이 정확하지 않습니다.'라는 문장을 출력한다. 오류가 없을 경우에만 else절이 수행된다.


## 오류 회피하기

프로그래밍을 하다 보면 특정 오류가 발생한 경우 그냥 통과시켜야 할 때가 있다.
아래 예시는 try문 안에서 FileNotFoundError가 발생할 경우에 pass를 사용하여 오류를 그냥 회피하도록 작성한 예제이다.
```python
>>> try:
>>>     f = open("나없는파일", 'r')
>>> except FileNotFoundError:
>>>     pass
```

## 오류 일부러 발생시키기
raise 명령어를 사용하면 오류를 강제로 발생시킬 수 있다.  

예를 들어, Bird 클래스를 상속받는 자식 클래스는 반드시 fly라는 함수를 구현하도록 강제하고 싶은 경우가 있을 수 있다.
다음과 같이 프로그램을 실행하면 Bird 클래스를 상속받는 자식 클래스는 반드시 fly함수를 구현해야한다.  
```python
>>> class Bird:
>>>     def fly(self):
>>>         raise NotImplementedError
```
> NotImplementedError는 파이썬 내장 오류로, 꼭 작성해야 하는 부분이 구현되지 않았을 경우 일부러 오류를 일으키기 위해 사용한다.

``` python
>>> class Eagle(Bird):
>>>     pass
>>> 
>>> eagle = Eagle()
>>> eagle.fly()
Traceback (most recent call last):
  File "...", line 33, in <module>
    eagle.fly()
  File "...", line 26, in fly
    raise NotImplementedError
NotImplementedError
```
위 예시에서 Eagle 클래스에서 fly 함수를 구현하지 않았기 때문에 Bird 클래스의 fly 함수가 호출되며, raise문에 의해 NotImplemented Error가 발생한다.  
  
NotImplementedError가 발생되지 않게 하려면 다음과 같이 Eagle 클래스에 fly 함수를 반드시 구현해야 한다.
``` python
>>> class Eagle(Bird):
>>>     def fly(self):
>>>         print("very fast")
>>> 
>>> eagle = Eagle()
>>> eagle.fly()
very fast
```
> 상속받는 클래스에서 함수를 재구현하는 것을 메서드 오버라이딩이라고 부른다.

## 예외 만들기
예외는 다음과 같이 파이썬 내장 클래스인 Exception 클래스를 상속하여 만들 수 있다.
```python
>>> class MyError(Exception):
>>>     pass
```
  
```python
>>> def say_nick(nick):
>>>     if nick == '바보':
>>>         raise MyError()
>>>     print(nick)
>>> say_nick("천사")
천사
>>> say_nick("바보")
Traceback (most recent call last):
  File "...", line 11, in <module>
    say_nick("바보")
  File "...", line 7, in say_nick
    raise MyError()
__main__.MyError
```
다음과 같이 별명을 출력해주는 함수를 작성하고 ```say_nick("바보")``` 입력하면 MyError가 발생한다.

  
위 예시를 예외 처리 기법을 사용하여 MyError 발생을 예외 처리 할 수도 있다.
``` python
>>> try:
>>>     say_nick("천사")
>>>     say_nick("바보")
>>> except MyError:
>>>     print("허용되지 않는 별명입니다.")
천사
허용되지 않는 별명입니다.
```
  
`print(e)`를 이용해 오류 메시지를 출력하고 싶다면 오류 클래스에 다음과 같은 `__str__` 메서드를 구현해야 한다. `__str__` 메서드는 print(e)처럼 오류 메시지를 print문으로 출력할 경우에 호출되는 메서드이다.
```python
>>> class MyError(Exception):
>>>     def __str__(self):
>>>         return "허용되지 않는 별명입니다."
```
```python
>>> try:
>>>     say_nick("천사")
>>>     say_nick("바보")
>>> except MyError as e:
>>>     print(e)
천사
허용되지 않는 별명입니다.
```
